[supervisord]
nodaemon=true

[program:Xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1080x720x24 &
autostart=true
autorestart=true
environment=DISPLAY=":99"

[program:openbox]
command=/usr/bin/openbox &
autostart=true
autorestart=true
environment=DISPLAY=":99"

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -rfbport 5901 -nopw -forever -shared &
autostart=true
autorestart=true
